package-manager: apt

directories:
 - ~/Documents/Universita
 - ~/Scripts


# Applications
applications:
  
  # Apt packages
  apt:
    - zenkit: 
        name: zenkit
        version: 1.1.1
  
  # Snap packages
  snap:
    - mailspring:
        name: mailspring
        version: 1.1.1
    - shotcut:
        name: shotcut
        version: 2.2.2

  # Flatpak packages
  flatpak:
    - openboard
    - postman
    - intellij

# General purpose tasks
tasks:

  oh-my-zsh: 
    name: oh-my-zsh
    description: "Installation of oh-my-zsh shell from github"
    commands:
      - cd ~
      - apt install git
      - git clone @aa:com